global.constants = {
  STATUS_TODO :'STATUS_TODO',
  STATUS_DOING:'STATUS_DOING',
  STATUS_DONE :'STATUS_DONE',

  STATUS_CODE : {
    STATUS_TODO: 'TODO',
    STATUS_DOING: 'DOING',
    STATUS_DONE: 'DONE'
   }
}