global.constants = {
  STATUS_TODO :'STATUS_TODO',
  STATUS_PROCESSING: 'STATUS_PROCESSING',
  STATUS_TESTING:'STATUS_TESTING',
  STATUS_DONE :'STATUS_DONE',
  STATUS_NOTPROCESSING: 'STATUS_NOTPROCESSING',

  STATUS_CODE : {
    STATUS_TODO: 'TODO',
    STATUS_PROCESSING: 'Processing',
    STATUS_TESTING: 'Testing',
    STATUS_DONE: 'DONE',
    STATUS_NOTPROCESSING: 'Not Process'
   },

   DOMAIN: 'localhost:8080'
}